import { test } from "node:test";
import assert from "node:assert/strict";
import { chmodSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DEFAULT_OPTIONS, OPTION_SPECS, validateOptions } from "../src/config.ts";
import { dafnyCheckDiff, dafnyVerifyArgs } from "../src/dafny-commands.ts";

function fixture(gen: string, proof: string, check: (g: string, p: string, dir: string) => void): void {
  const dir = mkdtempSync(join(tmpdir(), "lsc-git-review-"));
  try {
    const g = join(dir, "file.dfy.gen");
    const p = join(dir, "file.dfy");
    writeFileSync(g, gen);
    writeFileSync(p, proof);
    check(g, p, dir);
  } finally { rmSync(dir, { recursive: true, force: true }); }
}

function env(values: Record<string, string>, run: () => void): void {
  const before = Object.fromEntries(Object.keys(values).map(k => [k, process.env[k]]));
  try { Object.assign(process.env, values); run(); }
  finally {
    for (const [k, v] of Object.entries(before)) {
      if (v === undefined) delete process.env[k]; else process.env[k] = v;
    }
  }
}

test("identical content passes", () => fixture("method M() {}\n", "method M() {}\n", (g, p) => {
  assert.equal(dafnyCheckDiff(g, p), true);
}));
test("proof additions pass", () => fixture("method M() {}\n", "method M() {}\nlemma Proof() {}\n", (g, p) => {
  assert.equal(dafnyCheckDiff(g, p), true);
}));
test("generated modifications fail", () => fixture("method M() {}\n", "method Changed() {}\n", (g, p) => {
  assert.equal(dafnyCheckDiff(g, p), false);
}));
test("missing inputs fail closed", () => fixture("x\n", "x\n", (g, p, dir) => {
  assert.equal(dafnyCheckDiff(join(dir, "missing"), p), false);
  assert.equal(dafnyCheckDiff(g, join(dir, "missing")), false);
}));

test("forced Git color cannot hide deleted generated lines", () => {
  env({ GIT_CONFIG_COUNT: "1", GIT_CONFIG_KEY_0: "color.ui", GIT_CONFIG_VALUE_0: "always" }, () => {
    fixture("method M() {}\n", "method Changed() {}\n", (g, p) => assert.equal(dafnyCheckDiff(g, p), false));
    fixture("method M() {}\n", "method M() {}\nlemma Proof() {}\n", (g, p) => assert.equal(dafnyCheckDiff(g, p), true));
  });
});

test("binary detection cannot turn changed inputs into an additions-only pass", () => {
  fixture("before\0value\n", "after\0value\n", (g, p) => assert.equal(dafnyCheckDiff(g, p), false));
});

test("deletions beginning with dashes inside a hunk are not file headers", () => {
  fixture('const value := @"\n--before\n";\n', 'const value := @"\n--after\n";\n',
    (g, p) => assert.equal(dafnyCheckDiff(g, p), false));
});

test("external diff configuration is not executed for the proof guard", { skip: process.platform === "win32" }, () => {
  fixture("method M() {}\n", "method Changed() {}\n", (g, p, dir) => {
    const command = join(dir, "external-diff");
    writeFileSync(command, "#!/bin/sh\nprintf 'external output\\n'\nexit 0\n");
    chmodSync(command, 0o755);
    env({ GIT_EXTERNAL_DIFF: command }, () => assert.equal(dafnyCheckDiff(g, p), false));
  });
});

for (const script of ["exit 1", "printf 'not a patch\\n'; exit 1", "printf 'partial\\n'; exit 2"]) {
  test(`failed comparison is rejected: ${script}`, { skip: process.platform === "win32" }, () => {
    fixture("x\n", "y\n", (g, p, dir) => {
      const command = join(dir, "git");
      writeFileSync(command, `#!/bin/sh\n${script}\n`);
      chmodSync(command, 0o755);
      env({ PATH: dir }, () => assert.equal(dafnyCheckDiff(g, p), false));
    });
  });
}

test("missing Git executable is not success", () => {
  fixture("x\n", "y\n", (g, p, dir) => env({ PATH: dir }, () => assert.equal(dafnyCheckDiff(g, p), false)));
});

test("no header token uses the configuration default", () => {
  const explicit = dafnyVerifyArgs(`// lsc options: string-semantics=${DEFAULT_OPTIONS["string-semantics"]}\n`);
  assert.equal(explicit.error, undefined);
  assert.deepEqual(dafnyVerifyArgs("// Generated by lsc from a.ts\nmethod M() {}\n"), explicit);
  assert.deepEqual(dafnyVerifyArgs("method M() {}\n"), explicit);
});

test("every registered string model is accepted in the proof header", () => {
  for (const value of OPTION_SPECS["string-semantics"].values) {
    const result = dafnyVerifyArgs(`// lsc options: string-semantics=${value}\n`);
    assert.equal(result.error, undefined);
    assert.ok(result.args.includes(value === "javascript-utf16" ? "--unicode-char:false" : "--unicode-char:true"));
  }
});

test("javascript-utf16 selects code-unit chars and only the deprecation waiver", () => {
  const { args, error } = dafnyVerifyArgs("// Generated by lsc from a.ts\n// lsc options: string-semantics=javascript-utf16\n");
  assert.equal(error, undefined);
  assert.deepEqual(args, ["verify", "--unicode-char:false", "--allow-deprecation"]);
});

for (const secondModel of ["unicode-scalar", "javascript-utf16"]) {
  test(`duplicate proof options headers are rejected even when the second model is ${secondModel}`, () => {
    const result = dafnyVerifyArgs("// lsc options: string-semantics=javascript-utf16\n"
      + `// lsc options: string-semantics=${secondModel}\n`);
    assert.deepEqual(result.args, []);
    assert.match(result.error ?? "", /duplicate lsc options header/);
  });
  test(`duplicate string model tokens are rejected even when the second model is ${secondModel}`, () => {
    const result = dafnyVerifyArgs("// lsc options: string-semantics=javascript-utf16 "
      + `string-semantics=${secondModel}\n`);
    assert.deepEqual(result.args, []);
    assert.match(result.error ?? "", /duplicate string-semantics option/);
  });
}

test("proof additions cannot introduce UTF-16 over the generated scalar default", () => {
  const generated = "// Generated by lsc from a.ts\nmethod M() {}\n";
  fixture(generated, "// lsc options: string-semantics=javascript-utf16\n" + generated,
    (g, p) => assert.equal(dafnyCheckDiff(g, p), false));
});

test("proof additions cannot override a generated UTF-16 header", () => {
  const generated = "// Generated by lsc from a.ts\n"
    + "// lsc options: string-semantics=javascript-utf16\nmethod M() {}\n";
  fixture(generated, "// lsc options: string-semantics=unicode-scalar\n" + generated,
    (g, p) => assert.equal(dafnyCheckDiff(g, p), false));
  fixture(generated, generated + "\nlemma Proof() {}\n",
    (g, p) => assert.equal(dafnyCheckDiff(g, p), true));
});

for (const reference of [
  "import opened Std.Arithmetic.Mul",
  "function all(xs: seq<int>): bool { Std.Collections.Seq.All(xs, x => x > 0) }",
  "import opened Std \n . Arithmetic.Mul",
  "import opened Std /* proof comment */ .Arithmetic.Mul",
  "import opened Std // proof comment\n .Arithmetic.Mul",
  "import opened Std /* outer /* nested */ comment */ .Arithmetic.Mul",
  "function value'(): int { Std.Arithmetic.Mul.Value() }",
  String.raw`const quote: char := '"'; function value(): int { Std.Arithmetic.Mul.Value() }`,
  String.raw`const quote: char := '\''; function value(): int { Std.Arithmetic.Mul.Value() }`,
  String.raw`const character: char := '\u0053'; function value(): int { Std.Arithmetic.Mul.Value() }`,
  String.raw`const character: char := '\U{1_F600}'; function value(): int { Std.Arithmetic.Mul.Value() }`,
  "function value<'T>(): int { Std.Arithmetic.Mul.Value() }",
]) {
  test(`UTF-16 library diagnostic explains local helpers and proof additions: ${reference}`, () => {
    const { args, error } = dafnyVerifyArgs(`// lsc options: string-semantics=javascript-utf16\n${reference}\n`);
    assert.deepEqual(args, []);
    assert.match(error ?? "", /string-semantics/);
    assert.match(error ?? "", /Set "dafny-library": "local" in lemmascript\.json/);
    assert.match(error ?? "", /\/\/@ option dafny-library local/);
    assert.match(error ?? "", /lsc regen/);
    assert.match(error ?? "", /does not rewrite handwritten Std\.\* imports or calls/);
    assert.deepEqual(dafnyVerifyArgs(reference).args,
      ["verify", "--standard-libraries", "--unicode-char:true"]);
  });
}

for (const [description, content] of [
  ["ordinary string", 'const text: string := "Std.";'],
  ["escaped quotes", String.raw`const text: string := "quoted \"Std.\" text";`],
  ["escaped backslash before a quote", String.raw`const text: string := "backslash \\"; // Std.`],
  ["verbatim string", 'const text: string := @"quoted ""Std."" text";'],
  ["multiline verbatim string", 'const text: string := @"first line\nStd. on second line";'],
  ["line comment", "// Std.Arithmetic.Mul\nmethod M() {}"],
  ["block comment", "/* import opened Std.Arithmetic.Mul */\nmethod M() {}"],
  ["nested block comment", "/* outer /* Std.Arithmetic.Mul */ still a comment */\nmethod M() {}"],
  ["escaped character literal", String.raw`const quote: char := '\''; // Std.`],
  ["identifier suffix", "function f(): bool { NotStd.Collections.Seq.All([]) }"],
  ["identifier prefix", "function f(): bool { _Std.Collections.Seq.All([]) }"],
  ["digit suffix", "function f(): bool { Std2.Collections.Seq.All([]) }"],
  ["prime identifier", "function f(): bool { Std'.Collections.Seq.All([]) }"],
  ["question-mark identifier", "function f(): bool { Std?.Collections.Seq.All([]) }"],
  ["leading-apostrophe identifier", "function f(): bool { 'Std.Collections.Seq.All([]) }"],
  ["longest-match apostrophe identifier", "function f(): bool { 'x'Std.Collections.Seq.All([]) }"],
  ["sequence slice bound", "function slice(s: seq<int>, Std: int): seq<int> requires 0 <= Std <= |s| { s[Std..] }"],
]) {
  test(`Std. in ${description} does not select the standard library`, () => {
    assert.deepEqual(dafnyVerifyArgs(content),
      { args: ["verify", "--unicode-char:true"] });
    assert.deepEqual(dafnyVerifyArgs("// lsc options: string-semantics=javascript-utf16\n" + content),
      { args: ["verify", "--unicode-char:false", "--allow-deprecation"] });
  });
}

test("Unicode-scalar proofs can still use the standard library", () => {
  const { args, error } = dafnyVerifyArgs("import opened Std.Arithmetic.Mul\n");
  assert.equal(error, undefined);
  assert.deepEqual(args, ["verify", "--standard-libraries", "--unicode-char:true"]);
});

for (const token of ["string-semantics=utf8", "string-semantics=", "string-semantics"]) {
  test(`proof header uses config validation for invalid token: ${token}`, () => {
    const value = token.includes("=") ? token.slice(token.indexOf("=") + 1) : "";
    let message = "";
    assert.throws(() => validateOptions({ "string-semantics": value }, "generated header"), (error: Error) => {
      message = error.message;
      return true;
    });
    const result = dafnyVerifyArgs(`// lsc options: ${token}\n`);
    assert.deepEqual(result, { args: [], error: `ERROR: ${message}` });
    assert.match(result.error ?? "", /generated header: option 'string-semantics' must be one of:/);
  });
}

test("a later valid token does not hide an invalid string model", () => {
  assert.deepEqual(
    dafnyVerifyArgs("// lsc options: string-semantics=utf8 string-semantics=javascript-utf16\n"),
    dafnyVerifyArgs("// lsc options: string-semantics=utf8\n"),
  );
});

test("proof header settings are independent of the current project config", () => {
  fixture("", "", (_gen, _proof, dir) => {
    const previousDirectory = process.cwd();
    try {
      process.chdir(dir);
      for (const value of OPTION_SPECS["string-semantics"].values) {
        writeFileSync(join(dir, "lemmascript.json"), JSON.stringify({ "string-semantics": value }));
        assert.deepEqual(dafnyVerifyArgs("// lsc options: string-semantics=javascript-utf16\n").args,
          ["verify", "--unicode-char:false", "--allow-deprecation"]);
        assert.deepEqual(dafnyVerifyArgs("// lsc options: string-semantics=unicode-scalar\n").args,
          ["verify", "--unicode-char:true"]);
      }
    } finally { process.chdir(previousDirectory); }
  });
});

test("time limit and extra flags keep their positions before the char-mode pin", () => {
  assert.deepEqual(
    dafnyVerifyArgs("method M() {}\n", 30, "--isolate-assertions").args,
    ["verify", "--verification-time-limit", "30", "--isolate-assertions", "--unicode-char:true"],
  );
});
