// Generated by lsc from dual.ts

datatype Account = Account(member: bool, suspended: bool)

datatype Request = Request(account: Account)

function dual<A, B, R>(body: (A, B) -> R): (B) -> (A) -> R
{
  (that: B) => (self: A) => body(self, that)
}

lemma dual_ensures<A, B, R>(body: (A, B) -> R)
  ensures forall that: B, self: A :: ((var i_callee := (var i_callee := dual(body); i_callee(that)); i_callee(self)) == body(self, that))
{
}

function denyOverride<A>(self: (A) -> bool, denied: (A) -> bool): (A) -> bool
{
  (value: A) => (self(value) && !(denied(value)))
}

lemma denyOverride_ensures<A>(self: (A) -> bool, denied: (A) -> bool)
  ensures forall value: A :: ((var i_callee := denyOverride(self, denied); i_callee(value)) == (self(value) && !(denied(value))))
{
}

function mapInput<A, B>(self: (A) -> bool, project: (B) -> A): (B) -> bool
{
  (value: B) => self(project(value))
}

lemma mapInput_ensures<A, B>(self: (A) -> bool, project: (B) -> A)
  ensures forall value: B :: ((var i_callee := mapInput(self, project); i_callee(value)) == self(project(value)))
{
}

function curriedPolicy<A, B>(eligible: (A) -> bool, denied: (A) -> bool, project: (B) -> A): (B) -> bool
{
  var denyLast := dual((self: (A) -> bool, denied: (A) -> bool) => denyOverride(self, denied));
  var mapLast := dual((self: (A) -> bool, project: (B) -> A) => mapInput(self, project));
  var withDenial := denyLast(denied);
  var onInput := mapLast(project);
  onInput(withDenial(eligible))
}

lemma curriedPolicy_ensures<A, B>(eligible: (A) -> bool, denied: (A) -> bool, project: (B) -> A)
  ensures forall value: B :: ((var i_callee := curriedPolicy(eligible, denied, project); i_callee(value)) == (eligible(project(value)) && !(denied(project(value)))))
{
}

function callingFormsAgree<A, B>(eligible: (A) -> bool, denied: (A) -> bool, project: (B) -> A, value: B): bool
{
  var direct := mapInput(denyOverride(eligible, denied), project);
  var curried := curriedPolicy(eligible, denied, project);
  (direct(value) == curried(value))
}

lemma callingFormsAgree_ensures<A, B>(eligible: (A) -> bool, denied: (A) -> bool, project: (B) -> A, value: B)
  ensures callingFormsAgree(eligible, denied, project, value)
{
}

function canEnter(request: Request): bool
{
  var i_callee := curriedPolicy((account: Account) => account.member, (account: Account) => account.suspended, (request: Request) => request.account);
  i_callee(request)
}

lemma canEnter_ensures(request: Request)
  ensures (canEnter(request) == (request.account.member && !(request.account.suspended)))
{
}
