// Generated by lsc from utf16.ts
// lsc options: string-semantics=javascript-utf16

predicate SeqAll<T>(xs: seq<T>, p: T -> bool)
  decreases |xs|
{
  |xs| == 0 || (p(xs[0]) && SeqAll(xs[1..], p))
}

function emojiLength(): int
{
  |"\uD83D\uDE00"|
}

lemma emojiLength_ensures()
  ensures (emojiLength() == 2)
{
}

function emojiFirstCodeUnit(): int
{
  ("\uD83D\uDE00"[0..1][0] as int)
}

lemma emojiFirstCodeUnit_ensures()
  ensures (emojiFirstCodeUnit() == 55357)
{
}

function allTextIsNonempty(): bool
{
  SeqAll(["\uD83D\uDE00", "text"], (value: string) => (|value| > 0))
}

lemma allTextIsNonempty_ensures()
  ensures (allTextIsNonempty() == true)
{
}
